app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('getDistance/<start>/<finish>', views.getDistance, name='getDistance'),
    path('saveAPI/<key>', views.saveAPI, name='saveAPI'),
    path('removeAPIKEY', views.removeAPIKEY, name='removeAPIKEY'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

class Setup(models.Model):
    key = models.IntegerField(default=0)
    apikey = models.CharField(max_length=200)
    
    def __str__(self):
        return self.apikey
        

app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from app.models import Setup
import requests
import math

def index(request):
    if Setup.objects.filter(key=1).count() == 0:
        apikey = ""
    else: 
        apikey = Setup.objects.get(key=1)
    context = {'apikey': apikey}
    return render(request, "app/index.html", context)
  
def saveAPI(request, key):
    if Setup.objects.filter(id=1).count() == 1:
        replaceKey = Setup.objects.get(id=1)
        replaceKey.apikey = key
        replaceKey.save()
    else:
        Setup.objects.create(key=1, apikey=key)
    return HttpResponse("Key Saved")
    
def getDistance(request, start, finish):
    apikey = str(Setup.objects.get(key=1))
    linkStart = "https://maps.googleapis.com/maps/api/geocode/json?address=" + start + "&key=" + apikey
    geoStart = requests.get(linkStart).json()
    startLat = geoStart['results'][0]['geometry']['location']['lat']
    startLng = geoStart['results'][0]['geometry']['location']['lng']
    linkFinish = "https://maps.googleapis.com/maps/api/geocode/json?address=" + finish + "&key=" + apikey
    geoFinish = requests.get(linkFinish).json()
    finishLat = geoFinish['results'][0]['geometry']['location']['lat']
    finishLng = geoFinish['results'][0]['geometry']['location']['lng']
    deltaLat = finishLat - startLat
    deltaLng = finishLng - startLng
    radian = 3.141592654/180
    startLatR = startLat * radian
    sinL1 = math.sin(startLat * radian)
    sinL2 = math.sin(finishLat * radian)
    cosL1 = math.cos(startLat * radian)
    cosL2 = math.cos(finishLat * radian)
    cosL1L2 = math.cos((startLng * radian) - (finishLng * radian))
    d = math.acos((sinL1 * sinL2) + (cosL1 * cosL2 * cosL1L2))
    miles = 3959 * d
    start_address = geoStart['results'][0]['formatted_address']
    finish_address = geoFinish['results'][0]['formatted_address']
    context = {
        'start_address': start_address,
        'finish_address': finish_address,
        'miles': miles,
    }
    return render(request, "app/data.html", context)
    
def removeAPIKEY(request):
    key = Setup.objects.get(key=1)
    key.delete()
    return redirect("/")

app/templates/app/base.html
<!DOCTYPE html>
<html>
{% include 'app/head.html' %}

<body>
{% block content %}
{% endblock %}
</body>

</html>

app/templates/app/data.html
{% include 'app/head.html' %}
        <h3>There are {{ miles|floatformat:0 }} miles between</h3>
        <h3>{{ start_address }}</h3>
        <h4>and</h4>
        <h3>{{ finish_address }}</h3>

app/templates/app/head.html
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<title>Distance Calculator</title>

app/templates/app/index.html
{% extends 'app/base.html' %} {% block content %}

<div class="container">
    <h1>Distance Calculator</h1>
    <div class="row">
        <div class="col-lg-6">
            {% if apikey != "" %}
                <p>API Key: {{ apikey }}</p>
                <a href="{% url 'app:removeAPIKEY' %}"><button class="btn btn-default btn-xs">
                    Remove Key
                </button></a>
            {% else %}
                <p>Enter your Google Maps API Key</p>
                <form id="saveAPI" method="POST">
                    <div class="input-group">
                        <input id="key" type="text" class="form-control" value="{{ apikey }}">
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </span>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
    <br>
    {% if apikey != "" %}
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <p>Enter locations</p>
            <form id="getDistance" method="POST">
                <div class="input-group input-group-lg">
                    <span class="input-group-addon" id="sizing-addon1">Start</span>
                    <input id="start" type="text" class="form-control" name="start" aria-describedby="sizing-addon1">
                </div>
                <br>
                <div class="input-group input-group-lg">
                    <span class="input-group-addon" id="sizing-addon1">Destination</span>
                    <input id="finish" type="text" class="form-control" name="finish" aria-describedby="sizing-addon1">
                </div>
                <br>
                <button class="btn btn-default" type="submit">Submit</button>
            </form>
        </div>
    </div>
    <hr>
    {% endif %}
    <br>
    <div class="row">
        <div class="col-lg-6">
            <p id="result"></p>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $("#saveAPI").submit(function(e) {
        e.preventDefault();
        let apikey = $("#key").val();
        $.ajax({
            url: '/saveAPI/' + apikey,
            success: function(result){
                location.reload();
            }
        })
    })
    $("#getDistance").submit(function(e) {
        e.preventDefault();
        let start = $("#start").val();
        let finish = $("#finish").val();
        $.ajax({
            url: '/getDistance/' + start + '/' + finish,
            success: function(result){
                $('#result').html(result)
            }
        })
    })
})
</script>
{% endblock %}

app/templates/app/navbar.html
<!DOCTYPE html>
<html>
    <body>
    </body>
</html>        